# Generated by Django 5.2.12 on 2026-03-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_complaint_is_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='is_anonymous',
        ),
    ]
