# Generated by Django 5.2.12 on 2026-03-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_complaint_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='section',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='complaint',
            name='student_class',
            field=models.CharField(default='', max_length=50),
        ),
    ]
