# Generated by Django 5.2.12 on 2026-04-12 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_class_assigned_teacher_student_class'),
        ('dashboard', '0007_complaint_section_complaint_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.students')),
            ],
        ),
    ]
