# Generated by Django 5.2.12 on 2026-04-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_complaint_response_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='response',
        ),
    ]
