# Generated by Django 5.2.12 on 2026-04-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_complaint_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_response', models.TextField()),
            ],
        ),
    ]
