# Generated by Django 5.2.12 on 2026-04-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_teacher_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remarks', models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher_complaint',
            name='complaint_response',
            field=models.TextField(max_length=300),
        ),
    ]
