# Generated by Django 5.2.12 on 2026-04-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_teacher_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_Response',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
