# Generated by Django 5.2.12 on 2026-04-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_complaint_complaint_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher_complaint',
        ),
        migrations.DeleteModel(
            name='Teacher_Leave',
        ),
    ]
