# Generated by Django 5.2.12 on 2026-04-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_delete_teacher_complaint_delete_teacher_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_Response',
            new_name='Remarks',
        ),
    ]
