# Generated by Django 5.2.12 on 2026-04-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_rename_complaint_response_complaint_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
