# Generated by Django 5.2.12 on 2026-04-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_complaint_responded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='Remarks',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
