# Generated by Django 5.2.12 on 2026-04-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_leaverecord_remarks_leaverecord_responded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='File_upload',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='leave_files/'),
        ),
    ]
