# Generated by Django 5.2.12 on 2026-04-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_leaverecord_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverecord',
            name='File_upload',
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='Document',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to='leave_documents/'),
        ),
    ]
