# Generated by Django 5.2.12 on 2026-04-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_remove_leaverecord_file_upload_leaverecord_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverecord',
            name='Document',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='leave_documents/'),
        ),
    ]
