# Generated by Django 5.2.12 on 2026-04-24 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_leaverecord_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverecord',
            old_name='Document',
            new_name='document',
        ),
    ]
