# Generated by Django 5.2.12 on 2026-04-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_rename_document_leaverecord_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverecord',
            name='document',
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='File_upload',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='leave_files/'),
        ),
    ]
