# Generated by Django 5.2.12 on 2026-04-24 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_remove_leaverecord_document_leaverecord_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverecord',
            name='File_upload',
        ),
    ]
