# Generated by Django 5.2.12 on 2026-04-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_leaverecord_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='leave_proofs/'),
        ),
    ]
