# Generated by Django 5.2.12 on 2026-04-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_leaverecord_proof_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverecord',
            name='responded_at',
        ),
    ]
