# Generated by Django 5.2.12 on 2026-04-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_remove_complaint_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
