# Generated by Django 5.2.12 on 2026-04-29 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_complaint_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
