# Generated by Django 5.2.12 on 2026-03-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='section',
            field=models.CharField(default='', max_length=5),
        ),
    ]
