# Generated by Django 5.2.12 on 2026-03-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_teacher_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='class_assigned',
            new_name='student_class',
        ),
    ]
